// Research areas with their labels
export const researchAreas = [
  // Core Sciences
  { value: "biology", label: "Biology" },
  { value: "chemistry", label: "Chemistry" },
  { value: "physics", label: "Physics" },
  { value: "theoretical-physics", label: "Theoretical Physics" },
  { value: "mathematics", label: "Mathematics" },
  { value: "computer-science", label: "Computer Science" },
  { value: "engineering", label: "Engineering" },
  { value: "medicine", label: "Medicine" },
  { value: "psychology", label: "Psychology" },
  { value: "neuroscience", label: "Neuroscience" },
  { value: "astronomy", label: "Astronomy" },
  { value: "cosmology", label: "Cosmology" },
  { value: "earth-sciences", label: "Earth Sciences" },
  { value: "social-sciences", label: "Social Sciences" },
  { value: "analytical-chemistry", label: "Analytical Chemistry" },
  { value: "cell-biology", label: "Cell Biology" },
  { value: "pharmacology", label: "Pharmacology" },
  { value: "microbiology", label: "Microbiology" },
  { value: "biochemistry", label: "Biochemistry" },
  { value: "molecular-biology", label: "Molecular Biology" },
  { value: "genetics", label: "Genetics" },
  { value: "immunology", label: "Immunology" },
  { value: "anatomy", label: "Anatomy" },
  { value: "physiology", label: "Physiology" },
  { value: "pathology", label: "Pathology" },
  { value: "toxicology", label: "Toxicology" },
  { value: "epidemiology", label: "Epidemiology" },
  { value: "public-health", label: "Public Health" },
  { value: "cardiology", label: "Cardiology" },
  { value: "neurology", label: "Neurology" },
  { value: "oncology", label: "Oncology" },
  { value: "pediatrics", label: "Pediatrics" },
  { value: "geriatrics", label: "Geriatrics" },
  { value: "psychiatry", label: "Psychiatry" },
  { value: "biomedical-engineering", label: "Biomedical Engineering" },
  { value: "chemical-engineering", label: "Chemical Engineering" },
  { value: "civil-engineering", label: "Civil Engineering" },
  { value: "electrical-engineering", label: "Electrical Engineering" },
  { value: "mechanical-engineering", label: "Mechanical Engineering" },
  { value: "nuclear-physics", label: "Nuclear Physics" },
  { value: "astrophysics", label: "Astrophysics" },
  { value: "bioinformatics", label: "Bioinformatics" },
  { value: "cognitive-science", label: "Cognitive Science" },
  { value: "climatology", label: "Climatology" },
  { value: "climate-science", label: "Climate Science" },
  { value: "medicinal-chemistry", label: "Medicinal Chemistry" },
  { value: "environmental-chemistry", label: "Environmental Chemistry" },

  // Modern / Interdisciplinary
  { value: "data-science", label: "Data Science" },
  { value: "machine-learning", label: "Machine Learning" },
  { value: "artificial-intelligence", label: "Artificial Intelligence" },
  { value: "biotechnology", label: "Biotechnology" },
  { value: "nanotechnology", label: "Nanotechnology" },
  { value: "robotics", label: "Robotics" },
  { value: "quantum-computing", label: "Quantum Computing" },
  { value: "systems-biology", label: "Systems Biology" },
  { value: "synthetic-biology", label: "Synthetic Biology" },
  { value: "computational-biology", label: "Computational Biology" },
  { value: "materials-science", label: "Materials Science" },
  { value: "information-theory", label: "Information Theory" },
  { value: "cybernetics", label: "Cybernetics" },
  { value: "complexity-science", label: "Complexity Science" },
  { value: "systems-theory", label: "Systems Theory" },
  { value: "experimental-design", label: "Experimental Design" },
  { value: "metascience", label: "Metascience" },
  { value: "open-science", label: "Open Science" },
  { value: "citizen-science", label: "Citizen Science" },

  // Fringe / Speculative / Cosmic
  { value: "ufos", label: "UFOs & UAPs" },
  { value: "astrobiology", label: "Astrobiology" },
  { value: "exoplanets", label: "Exoplanets" },
  { value: "quantum-biology", label: "Quantum Biology" },
  { value: "parapsychology", label: "Parapsychology" },
  { value: "telepathy", label: "Telepathy" },
  { value: "precognition", label: "Precognition" },
  { value: "psychokinesis", label: "Psychokinesis" },
  { value: "consciousness", label: "Consciousness Studies" },
  { value: "noetics", label: "Noetic Sciences" },
  { value: "panpsychism", label: "Panpsychism" },
  { value: "anomalous-cognition", label: "Anomalous Cognition" },
  { value: "biofield-science", label: "Biofield Science" },
  { value: "simulation-theory", label: "Simulation Theory" },
  { value: "transhumanism", label: "Transhumanism" },
  { value: "cryptozoology", label: "Cryptozoology" },

  // Philosophy & Epistemology
  { value: "epistemology", label: "Epistemology" },
  { value: "philosophy-of-science", label: "Philosophy of Science" },
  { value: "metaphysics", label: "Metaphysics" },
  { value: "ontology", label: "Ontology" },
  { value: "philosophy-of-mind", label: "Philosophy of Mind" },
  { value: "philosophy-of-nature", label: "Philosophy of Nature" },
  { value: "philosophy-of-technology", label: "Philosophy of Technology" },
  { value: "logic", label: "Logic" },
  { value: "ethics", label: "Ethics" },
  { value: "aesthetics", label: "Aesthetics" },
  { value: "phenomenology", label: "Phenomenology" },
  { value: "hermeneutics", label: "Hermeneutics" },
  { value: "philosophy-of-language", label: "Philosophy of Language" },
  { value: "methodological-pluralism", label: "Methodological Pluralism" },
  { value: "experimental-philosophy", label: "Experimental Philosophy" },

  // Theology, Mysticism, and Esotericism
  { value: "theology", label: "Theology" },
  { value: "comparative-religion", label: "Comparative Religion" },
  { value: "mysticism", label: "Mysticism" },
  { value: "gnosticism", label: "Gnosticism" },
  { value: "hermeticism", label: "Hermeticism" },
  { value: "alchemy", label: "Alchemy" },
  { value: "occult-studies", label: "Occult Studies" },
  { value: "esotericism", label: "Esotericism" },
  { value: "theosophy", label: "Theosophy" },
  { value: "sacred-geometry", label: "Sacred Geometry" },
  { value: "symbolism", label: "Symbolism" },
  { value: "mythology", label: "Mythology" },
  { value: "spiritual-philosophy", label: "Spiritual Philosophy" },
  { value: "metaphysical-theology", label: "Metaphysical Theology" },
  { value: "religious-experience", label: "Religious Experience" },

  // Consciousness & Inner Sciences
  { value: "psychonautics", label: "Psychonautics" },
  { value: "dream-studies", label: "Dream Studies" },
  { value: "lucid-dreaming", label: "Lucid Dreaming" },
  { value: "psychedelic-studies", label: "Psychedelic Studies" },
  { value: "altered-states", label: "Altered States" },
  { value: "meditation-science", label: "Meditation Science" },
  { value: "embodiment-studies", label: "Embodiment Studies" },
  { value: "integral-theory", label: "Integral Theory" },
  { value: "phenomenal-consciousness", label: "Phenomenal Consciousness" },

  // Arts & Expression
  { value: "art", label: "Art" },
  { value: "art-theory", label: "Art Theory" },
  { value: "musicology", label: "Musicology" },
  { value: "creative-writing", label: "Creative Writing" },
  { value: "architecture", label: "Architecture" },
  { value: "design", label: "Design" },
  { value: "visual-arts", label: "Visual Arts" },
  { value: "film-studies", label: "Film Studies" },
  { value: "performance-studies", label: "Performance Studies" },
  { value: "aesthetic-philosophy", label: "Aesthetic Philosophy" },

  // Cultural / Historical / Symbolic
  { value: "anthropology", label: "Anthropology" },
  { value: "archaeology", label: "Archaeology" },
  { value: "history-of-science", label: "History of Science" },
  { value: "philosophy-of-history", label: "Philosophy of History" },
  { value: "linguistics", label: "Linguistics" },
  { value: "cultural-studies", label: "Cultural Studies" },
  { value: "mythopoetics", label: "Mythopoetics" },
  { value: "futurism", label: "Futurism" },
  { value: "posthumanism", label: "Posthumanism" },
  { value: "metamodernism", label: "Metamodernism" },
].sort((a, b) => a.label.localeCompare(b.label))

// Each category has a UNIQUE color - no duplicates!
export const scienceCategoryColors: Record<string, { bg: string; text: string }> = {
  // Core Sciences - 14 unique colors
  "biology": { bg: "bg-[#38B000]", text: "text-white" },
  "chemistry": { bg: "bg-[#FF5400]", text: "text-white" },
  "physics": { bg: "bg-[#FFD60A]", text: "text-black" },
  "theoretical-physics": { bg: "bg-[#FFA500]", text: "text-white" },
  "mathematics": { bg: "bg-[#7209B7]", text: "text-white" },
  "computer-science": { bg: "bg-[#3A86FF]", text: "text-white" },
  "engineering": { bg: "bg-[#4361EE]", text: "text-white" },
  "medicine": { bg: "bg-[#FF0054]", text: "text-white" },
  "psychology": { bg: "bg-[#FB5607]", text: "text-white" },
  "neuroscience": { bg: "bg-[#9D4EDD]", text: "text-white" },
  "astronomy": { bg: "bg-[#3F37C9]", text: "text-white" },
  "cosmology": { bg: "bg-[#1E3A8A]", text: "text-white" },
  "earth-sciences": { bg: "bg-[#2DC653]", text: "text-white" },
  "social-sciences": { bg: "bg-[#F97316]", text: "text-white" },

  // Additional common categories that might be in the database
  "analytical-chemistry": { bg: "bg-[#FF6B35]", text: "text-white" },
  "cell-biology": { bg: "bg-[#4CAF50]", text: "text-white" },
  "pharmacology": { bg: "bg-[#9C27B0]", text: "text-white" },
  "microbiology": { bg: "bg-[#8BC34A]", text: "text-white" },
  "biochemistry": { bg: "bg-[#FF9800]", text: "text-white" },
  "molecular-biology": { bg: "bg-[#4CAF50]", text: "text-white" },
  "genetics": { bg: "bg-[#2196F3]", text: "text-white" },
  "immunology": { bg: "bg-[#E91E63]", text: "text-white" },
  "anatomy": { bg: "bg-[#F44336]", text: "text-white" },
  "physiology": { bg: "bg-[#FF5722]", text: "text-white" },
  "pathology": { bg: "bg-[#795548]", text: "text-white" },
  "toxicology": { bg: "bg-[#607D8B]", text: "text-white" },
  "epidemiology": { bg: "bg-[#3F51B5]", text: "text-white" },
  "public-health": { bg: "bg-[#009688]", text: "text-white" },
  "cardiology": { bg: "bg-[#E91E63]", text: "text-white" },
  "neurology": { bg: "bg-[#673AB7]", text: "text-white" },
  "oncology": { bg: "bg-[#FF1744]", text: "text-white" },
  "pediatrics": { bg: "bg-[#FF4081]", text: "text-white" },
  "geriatrics": { bg: "bg-[#FF5722]", text: "text-white" },
  "psychiatry": { bg: "bg-[#FF9800]", text: "text-white" },
  "biomedical-engineering": { bg: "bg-[#3F51B5]", text: "text-white" },
  "chemical-engineering": { bg: "bg-[#FF6F00]", text: "text-white" },
  "civil-engineering": { bg: "bg-[#795548]", text: "text-white" },
  "electrical-engineering": { bg: "bg-[#FFC107]", text: "text-black" },
  "mechanical-engineering": { bg: "bg-[#607D8B]", text: "text-white" },
  "artificial-intelligence": { bg: "bg-[#3A86FF]", text: "text-white" },
  "robotics": { bg: "bg-[#3B82F6]", text: "text-white" },
  "nanotechnology": { bg: "bg-[#818CF8]", text: "text-white" },
  "materials-science": { bg: "bg-[#64748B]", text: "text-white" },
  "systems-biology": { bg: "bg-[#22C55E]", text: "text-white" },
  "synthetic-biology": { bg: "bg-[#14B8A6]", text: "text-white" },
  "computational-biology": { bg: "bg-[#84CC16]", text: "text-white" },
  "quantum-computing": { bg: "bg-[#A855F7]", text: "text-white" },
  "renewable-energy": { bg: "bg-[#2DC653]", text: "text-white" },
  "sustainable-development": { bg: "bg-[#2DC653]", text: "text-white" },
  "data-science": { bg: "bg-[#8B5CF6]", text: "text-white" },
  "astrobiology": { bg: "bg-[#3F37C9]", text: "text-white" },
  "nuclear-physics": { bg: "bg-[#FF5722]", text: "text-white" },
  "astrophysics": { bg: "bg-[#673AB7]", text: "text-white" },
  "bioinformatics": { bg: "bg-[#4CAF50]", text: "text-white" },
  "cognitive-science": { bg: "bg-[#FF9800]", text: "text-white" },
  "climatology": { bg: "bg-[#00BCD4]", text: "text-white" },
  "climate-science": { bg: "bg-[#009688]", text: "text-white" },
  "medicinal-chemistry": { bg: "bg-[#E91E63]", text: "text-white" },
  "environmental-chemistry": { bg: "bg-[#2E7D32]", text: "text-white" },

  // Modern / Interdisciplinary - 19 unique colors
  "machine-learning": { bg: "bg-[#0EA5E9]", text: "text-white" },
  "biotechnology": { bg: "bg-[#10B981]", text: "text-white" },
  "information-theory": { bg: "bg-[#0284C7]", text: "text-white" },
  "cybernetics": { bg: "bg-[#1D4ED8]", text: "text-white" },
  "complexity-science": { bg: "bg-[#C026D3]", text: "text-white" },
  "systems-theory": { bg: "bg-[#2563EB]", text: "text-white" },
  "experimental-design": { bg: "bg-[#475569]", text: "text-white" },
  "metascience": { bg: "bg-[#334155]", text: "text-white" },
  "open-science": { bg: "bg-[#059669]", text: "text-white" },
  "citizen-science": { bg: "bg-[#16A34A]", text: "text-white" },

  // Fringe / Speculative / Cosmic - 16 unique colors
  "ufos": { bg: "bg-[#5B21B6]", text: "text-white" },
  "exoplanets": { bg: "bg-[#6D28D9]", text: "text-white" },
  "quantum-biology": { bg: "bg-[#7E22CE]", text: "text-white" },
  "parapsychology": { bg: "bg-[#C77DFF]", text: "text-white" },
  "telepathy": { bg: "bg-[#E0AAFF]", text: "text-black" },
  "precognition": { bg: "bg-[#BE95FF]", text: "text-black" },
  "psychokinesis": { bg: "bg-[#D8B4FE]", text: "text-black" },
  "consciousness": { bg: "bg-[#A78BFA]", text: "text-white" },
  "noetics": { bg: "bg-[#9333EA]", text: "text-white" },
  "panpsychism": { bg: "bg-[#C4B5FD]", text: "text-black" },
  "anomalous-cognition": { bg: "bg-[#DDD6FE]", text: "text-black" },
  "biofield-science": { bg: "bg-[#A3E635]", text: "text-black" },
  "simulation-theory": { bg: "bg-[#6366F1]", text: "text-white" },
  "transhumanism": { bg: "bg-[#4C1D95]", text: "text-white" },
  "cryptozoology": { bg: "bg-[#15803D]", text: "text-white" },

  // Philosophy & Epistemology - 15 unique colors
  "epistemology": { bg: "bg-[#D97706]", text: "text-white" },
  "philosophy-of-science": { bg: "bg-[#F59E0B]", text: "text-white" },
  "metaphysics": { bg: "bg-[#B45309]", text: "text-white" },
  "ontology": { bg: "bg-[#EA580C]", text: "text-white" },
  "philosophy-of-mind": { bg: "bg-[#FB923C]", text: "text-white" },
  "philosophy-of-nature": { bg: "bg-[#65A30D]", text: "text-white" },
  "philosophy-of-technology": { bg: "bg-[#71717A]", text: "text-white" },
  "logic": { bg: "bg-[#7C3AED]", text: "text-white" },
  "ethics": { bg: "bg-[#991B1B]", text: "text-white" },
  "aesthetics": { bg: "bg-[#E11D48]", text: "text-white" },
  "phenomenology": { bg: "bg-[#92400E]", text: "text-white" },
  "hermeneutics": { bg: "bg-[#A16207]", text: "text-white" },
  "philosophy-of-language": { bg: "bg-[#CA8A04]", text: "text-white" },
  "methodological-pluralism": { bg: "bg-[#78716C]", text: "text-white" },
  "experimental-philosophy": { bg: "bg-[#EF4444]", text: "text-white" },

  // Theology, Mysticism, and Esotericism - 15 unique colors
  "theology": { bg: "bg-[#581C87]", text: "text-white" },
  "comparative-religion": { bg: "bg-[#6B21A8]", text: "text-white" },
  "mysticism": { bg: "bg-[#5A189A]", text: "text-white" },
  "gnosticism": { bg: "bg-[#701A75]", text: "text-white" },
  "hermeticism": { bg: "bg-[#9A3412]", text: "text-white" },
  "alchemy": { bg: "bg-[#B91C1C]", text: "text-white" },
  "occult-studies": { bg: "bg-[#7F1D1D]", text: "text-white" },
  "esotericism": { bg: "bg-[#831843]", text: "text-white" },
  "theosophy": { bg: "bg-[#86198F]", text: "text-white" },
  "sacred-geometry": { bg: "bg-[#FBBF24]", text: "text-black" },
  "symbolism": { bg: "bg-[#A21CAF]", text: "text-white" },
  "mythology": { bg: "bg-[#9F1239]", text: "text-white" },
  "spiritual-philosophy": { bg: "bg-[#BE123C]", text: "text-white" },
  "metaphysical-theology": { bg: "bg-[#4A044E]", text: "text-white" },
  "religious-experience": { bg: "bg-[#881337]", text: "text-white" },

  // Consciousness & Inner Sciences - 9 unique colors
  "psychonautics": { bg: "bg-[#F0ABFC]", text: "text-black" },
  "dream-studies": { bg: "bg-[#E879F9]", text: "text-white" },
  "lucid-dreaming": { bg: "bg-[#D946EF]", text: "text-white" },
  "psychedelic-studies": { bg: "bg-[#F9A8D4]", text: "text-black" },
  "altered-states": { bg: "bg-[#F472B6]", text: "text-white" },
  "meditation-science": { bg: "bg-[#0891B2]", text: "text-white" },
  "embodiment-studies": { bg: "bg-[#FB8500]", text: "text-white" },
  "integral-theory": { bg: "bg-[#DB2777]", text: "text-white" },
  "phenomenal-consciousness": { bg: "bg-[#BE185D]", text: "text-white" },

  // Arts & Expression - 10 unique colors
  "art": { bg: "bg-[#E5383B]", text: "text-white" },
  "art-theory": { bg: "bg-[#F87171]", text: "text-white" },
  "musicology": { bg: "bg-[#EC4899]", text: "text-white" },
  "creative-writing": { bg: "bg-[#FDBA74]", text: "text-black" },
  "architecture": { bg: "bg-[#52525B]", text: "text-white" },
  "design": { bg: "bg-[#14B8A6]", text: "text-white" },
  "visual-arts": { bg: "bg-[#F43F5E]", text: "text-white" },
  "film-studies": { bg: "bg-[#FB7185]", text: "text-white" },
  "performance-studies": { bg: "bg-[#FD7E14]", text: "text-white" },
  "aesthetic-philosophy": { bg: "bg-[#DC2626]", text: "text-white" },

  // Cultural / Historical / Symbolic - 10 unique colors
  "anthropology": { bg: "bg-[#9A6324]", text: "text-white" },
  "archaeology": { bg: "bg-[#B87333]", text: "text-white" },
  "history-of-science": { bg: "bg-[#78350F]", text: "text-white" },
  "philosophy-of-history": { bg: "bg-[#854D0E]", text: "text-white" },
  "linguistics": { bg: "bg-[#EF6C00]", text: "text-white" },
  "cultural-studies": { bg: "bg-[#F57C00]", text: "text-white" },
  "mythopoetics": { bg: "bg-[#7C2D12]", text: "text-white" },
  "futurism": { bg: "bg-[#0369A1]", text: "text-white" },
  "posthumanism": { bg: "bg-[#075985]", text: "text-white" },
  "metamodernism": { bg: "bg-[#E65100]", text: "text-white" },
}
